### ISSUE TITLE
Getting reference to DOM element for a given Node

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#183]
We need API to get reference to DOM element for a given Node with DOMElement component attached.

I'm trying to do something like `React.render(<SomeComponent/>, toThisElement)`

**Comment by pilwon** [comment]
Workaround @zackbrown shared on Slack:

```js
//for a given Node, returns a reference to the DOM Node associated with the DOMElement attached to that Node.
//returns undefined if no DOM Node associated with Node or if DOM Node is detached from document.
//throws if called from a web worker.
function getDOMNodeFromNode(node){
	return document.querySelector('[data-fa-path=\"'+node.getId()+'\"]');
}
```

**Comment by pilwon** [comment]
To use attribute selector I'd need to wait until `CHANGE_ATTRIBUTE` event for `data-fa-path` in `DOMElement`'s internal MQ is flushed and successfully processed by `DOMRenderer`. How could I set up this hook?

We'd need `DOMRenderer.prototype.setAttribute` emit some event back to `DOMElement` so it could notify the callback handler.

Also, the above script fails when the original selector passed to the scene contains double quotes. We'd need to handle this case before adding that function to engine.

**Comment by pilwon** [comment]
Promise version of workaround using polling to wait for its availability:

```js
function waitForDOMElementFromNodePromise(node) {
  return new Promise((resolve) => {
    (function query() {
      let nodeId = node.getLocation();
      let elements = document
        .querySelector(nodeId.split('/')[0])
        .querySelectorAll('[data-fa-path]');
      for (let i = 0; i < elements.length; ++i) {
        if (elements[i].getAttribute('data-fa-path') === nodeId) {
          return resolve(elements[i]);
        }
      }
      setTimeout(query, 16);
    })();
  });
}

waitForDOMElementFromNodePromise(node).then((element) => {
  // ...
});
```

Ideally we want API for something like this where it uses internal messaging (`DOMRenderer` notifying `DOMElement`) instead of polling like this one.

**Comment by DnMllr** [comment]
@pilwon It sounds like you would like to create a scene within a specific DOM element. My understanding of `React.render` is that it allows you to render a particular react component to a specific element.  For this case, you can call `FamousEngine.createScene( [ the element's selector ] )` and that will instantiate the scene within the target element into which you can render anything you'd like.

Does that help?

**Comment by pilwon** [comment]
@DnMllr I'd like to do something like this:

```
+ React Component (R1)
  + Famous Scene (F1)
    + Famous Node w/ DOMElement component attached (F2)
      + React Component (R2)
        ...
```
R1 can render F1 and F2 into specific element built with R1 using `FamousEngine.createScene(selector)` but I'd need reference to F2's `<div/>` in order to `React.render(<R2/>, intoTheElementManagedByF2)`.

**Comment by alexanderGugel** [comment]
@DnMllr I think he just wants to get the **real** Element associated with a DOMElement.

Currently, there is no non-hacky way to do that.

One possibility is to lookup the DOMElement's `ElementCache` via the `Node`'s path. You can achieve this by:

1. Retrieving the appropriate Context via the Compositor
2. Getting the node's path after the DOMElement has been instantiated
3. Looking up the ElementCache via `DOMRenderer._elements[path]`

**Comment by gadicc** [comment]
Haha, a promise watcher, nice :>  I guess we'll be hitting a few of the same problems.  I did something much hackier, by never calling `setContent()` directly and adding a component with a variation of it.  Not a great pattern, I know, but was also keen to just get going :)

```js
  var path = node.getId();
  var context = path.split('/', 1)[0];
  var domRenderer = FamousEngine.compositor.getOrSetContext(context).DOMRenderer;

  var id = node.addComponent({
    onUpdate: function(time) {
      domRenderer.loadPath(path);
      domRenderer.findTarget();
      if (domRenderer._target) {
        domRenderer.findChildren();

        domRenderer._target.content = document.createElement('div');
        domRenderer._target.content.classList.add('famous-dom-element-content');
        domRenderer._target.element.insertBefore(
            domRenderer._target.content,
            domRenderer._target.element.firstChild
        );

        // This never gets called again, Blaze updates the parts of the DOM that changed directly.
        Blaze.render(
          blazeView.templateContentBlock,
          domRenderer._target.content,
          blazeView
        );

        domRenderer.setSize(
          domRenderer._target.explicitWidth ? false : domRenderer._target.size[0],
          domRenderer._target.explicitHeight ? false : domRenderer._target.size[1]
        );
      } else {
        node.requestUpdate(id);
      }
    }
  });
  node.requestUpdate(id);
```

**Comment by DnMllr** [comment]
@gadicc I would really recommend not working with the DOMRenderer directly it isn't considered to be part of the public api. For example, `domRenderer.findChildren` will be removed from the platform with pr #58 which is something that I've been working very hard to achieve as `.findChildren` is probably the single worst part of the engine currently. 

@pilwon and @gadicc: It's obvious that we need an offering to allow for the sort of integrations that are attempting to be achieved here. This is not a small task, unfortunately, as the platform was made to be abstracted away from the DOM itself. I'll describe some of the problems that we face in making this sort of thing possible and then propose a solution for the future and a solution for the present.

* **challenges**

1. If we promote an environment where the user doesn't have to care about the DOM itself then we can fine tune operations without worrying about the specifics of the document. This shows itself already because there is a many-to-one relationship between elements in the DOM and our DOMElement components. If a DOMElement should leave the scene graph, or if the scene graph gets restructured, we leave the DOM where it is so that it can be repurposed later for another DOMElement. _This means that single elements may not have a consistent representation within the Famous scene graph._ Furthermore, in the future there may be a many-to-may relationship between DOMElement components and DOM elements. This case may arise when two subtrees are being swapped. It would be far cheaper to just swap the association between the component and the element rather than removing and appending subtrees of elements to actually complete the swap. This is the sort of optimization that we want to be able achieve (and note: to my knowledge, React does this sort of thing already).

2. We want to maintain the portability of the platform so that it can exist in environments where the document doesn't, such as in a worker or on a server. Adding functionality to the DOMElement component itself is something that I don't believe we can accommodate for that reason.

3. It is possible that the Famous Engine can unexpectedly draw over what React or Meteor does in our elements, or, similarly, that React and Meteor can draw over what we do in our elements. It'll take a good deal of care to make sure that in all cases that this does not happen. Without a doubt the first step is not to target the element itself, but either target the element's content child div (which will be the child with the class '.famous-dom-element-content') or create a new child within the element to let another renderer draw to.

* **immediate solution**

The first thing to keep in mind is that Node's are ephemeral, but their paths are absolute. Nodes can potentially move all over the place in the scene graph, but every position in the hierarchy has a single representation in path. You can access the path of a node by calling `Node.getLocation`.

1. Create a component on your node that queries for the path in the scene graph at which you want to allow React or Meteor to render to.
2. It should watch for the onMount event to handle the case where the node is moving in the scene graph. When it does, it needs to remove the query class/id and do what it takes to clean up what React or Meteor put on the element. Then needs to reapply the query class/id and invite React or Meteor to render to a new element that has `position: absolute` inside of the element returned by `document.querySelector( class/id )`.

Note that this won't allow you to have your code inside of a web worker.

This strategy is probably the safest bet for the moment, though it is more work. If you just want to mess around or you can guarantee that the scene graph isn't really changing and only need to render React or Blaze once or twice: I would recommend doing the sort of thing that @pilwon commented a day ago but with two small changes:

```javascript

var clock = FamousEngine.getClock();

function waitForDOMElementFromNodePromise(node) {
  return new Promise((resolve) => {
    (function query() {
      let nodeId = node.getLocation();
      let elements = document
        .querySelector(nodeId.split('/')[0])
        .querySelectorAll('[data-fa-path]');
      for (let i = 0; i < elements.length; ++i) {
        if (elements[i].dataSet.faPath === nodeId) {
          return resolve(elements[i]);
        }
      }
      clock.setTimeout(query, 16);
    })();
  });
}

waitForDOMElementFromNodePromise(node).then((element) => {
   // make sure you add content inside of a child. Clean up this child when you need to.
  var child = element.appendChild(document.createElement('div'));
  // ...
});
```

`Clock.setTimeout` will sync this operation to the famous frame constraining DOM queries to the time in which we are already altering the dom. Make sure that the content div you create here has position absolute and take care to figure out its sizing needs and then you should be ok.

* **long term solution**

Long term we should probably have some sort of events on the DOMElement component which alerts whenever anything changes in the DOM and also hooks in the renderer side for allowing custom rendering. When the DOMRenderer renders a famous element to a particular div you should be able to hook into that and append your own process. This is something that we can support and I can personally own that or something along those lines after my current task (getting in #58).

**Comment by gadicc** [comment]
Hey @DnMllr, thanks for the detailed reply.  It's great hearing about the finer details in the architecture, which I think is important for me to understand as an integration developer.  If there's any further reading on the engine design, I'd love a link... although I am gradually understanding it all just from going through the code.

I have quite a few questions, but I think instead I'll accept your kind offer to prioritize this and not waste time on questions with transient relevance :>

For now though I still need to use the domRenderer, since it lets me set the size for when RENDER_SIZE is used (so any long term solution needs a way to tell domRenderer to check the size on `_target.content` again).  The code is based on `DOMRenderer.setContent()`, so when your PR is merged, I'll just remove the `findChilden()` call like you do.  Great job on the PR, btw... I see it mentioned as the solution for a great number of open issues!

**Comment by FarhadG** [comment]
What's the status on this issue and its corresponding PR?

@michaelobriena @DnMllr @alexanderGugel

**Comment by alexanderGugel** [comment]
My corresponding PR has not been merged. I'm still against the proposed solution of adding this functionality to the DOMRenderer. I think this should be labeled as "wontfix", because even if we implement the solution proposed by @DnMllr, we won't support getting the native element associated with a "Famous" DOMElement.

**Comment by michaelobriena** [comment]
After discussing this internally, this is something that we will be supporting but not through the DOMElement.

There are a few reasons why we do not want this code to be tied to the DOM element:
- Breaks if application code is run in a web worker
- Breaks if application code is run on a server/other computer
- Because we pool elements any DOM element you would receive cannot be guaranteed to be the DOM element for the life of the application

What the solution will be is a way to register callbacks on the DOMRenderer.  We can then call these callbacks during various lifecycle events throughout the program.  Because every node has a unique path and a way to get that path, a user can understand when the associated DOM element is mounted, unmounted, switched, and everything a user would need to successfully work with the DOM element.

I understand this is more work for the user to implement but the ability to query for the element associated with a Node goes against a main point for Famous, and majority of more modern web rendering engines for that part, abstracting away the DOM.  The biggest issue, as mentioned above, is that modern web rendering engines need to pool DOM elements in order to be performant.  Because of this we cannot guarantee that if you are mutating you scene graph that the result of .getElement() would be the same every time you called it.  If we did make that guarantee possible by opting out of the pooling, via a flag or something, then we have introduced a feature in the system that is very niche, less performant, and adds to maintenance costs without a real gain in our opinion.

We understand this is a feature that is being heavily requested and will actively be working on the solution with DOMRenderer events.

**Comment by gadicc** [comment]
Thanks @michaelobriena, @DnMllr and @alexanderGugel for all the time debating the best implementation of this (and the various PRs and explanations along the way!).

From my side (famous-views integration), this makes perfect sense and provides exactly what I'll need to properly manage what's happening.  I'd imagine @pilwon feels the same?  I guess I should maybe note though that these kind of integrations are generally responsible for managing the Node that contains the DOMElement too (and as such, can clean-up appropriately before the Node is ever removed), but supporting the events beyond onMount definitely allow for more flexible patterns.

For everyone else (do we have a list of use cases?) I think you'll need to (in the medium term) dedicate a page to this somewhere, explaining why it's potentially a bad idea to take on the responsibility, and why such a complex solution was necessary.  If I may, I'd suggest even boilerplate code with callbacks for all the events with example handling and explanatory comments.  I can just imagine a lot of people struggling with this, for something as simple as using a jQuery plugin (the pros/cons of which can be left as an exercise for the developer).

**Comment by gadicc** [comment]
Yay, #276 landed in 0.7!  @pilwon, does this work for you / can we close this?

@alexanderGugel, is there a recommended way to get the domRenderer to update the size of RENDER_SIZE'd nodes?  My current hacky way is just doing what `setContent()` does:

```js
domRenderer.setSize(
  domRenderer._target.explicitWidth ? false : domRenderer._target.size[0],
  domRenderer._target.explicitHeight ? false : domRenderer._target.size[1]
);
```

**Comment by alexanderGugel** [comment]
@gadicc 

Currently there is no API for that, although I see a use case there. Ideally it shouldn't be necessary in the first place to "re"-rendersize DOMElements.

**Comment by elinfante** [comment]
Thank you for this thread. It was very useful!!!
For my problem I needed to draw an SVG using Snapsvg and in order to do that I had to target the native DOM. Following the code I used just in case someone else finds it useful:

`function createSVG() {

  //Node
  this.svgNode = this.node.addChild();
  this.svgNode.setSizeMode(Size.ABSOLUTE,Size.ABSOLUTE);   
  this.svgNode.setAbsoluteSize(200,200);
  this.svgNode.setPosition(0,0);
  
  //DOM Element
  this.svg = new DOMElement(this.svgNode);
  this.svg.setAttribute('style', 'background:red;');

  //Search native DOM Element of the Famous DOM I just created above (this.svg)
  waitForDOMElementFromNodePromise.call(this, this.svgNode).then((element) => {

    //At this point I have targeted the DOM so I create an empty SVG to use Snap afterwards.
    var svg = element.appendChild(document.createElementNS("http://www.w3.org/2000/svg", "svg"));
    svg.setAttribute('width',200);
    svg.setAttribute('height',200);
    console.log ("%c -> ", "background:#ff0000;", "I HAVE TARGETED THE native DOM --->>", element);     

    //I can target the native DOM 
    //so let's use Snap to create the svg.
    var s = new Snap(svg);
    var bigCircle = s.circle(100, 100, 100);

  });


}`

**Comment by alexanderGugel** [comment]
As a final summary of this issue:
1. We do not want to encourage users to access "native" elements, since it breaks the abstraction that allows us to run in a web worker (or any environment that doesn't prove direct access to the `document` singleton).
2. As discussed in this thread, there are a number of "hacks" around it that basically rely on the `famous` data attribute that is being used whenever a DOMElement is being rendered.
3. Lifecycle events (#276) that hook into the DOMRenderer solve **some** of the use cases that typically require access to elements.

@michaelobriena Do you have final thoughts on this or are you ok with closing this? I think we have made it clear that this is in some way an anti-feature that we don't want to implement the way it was proposed. Feel free to reopen if you feel otherwise.
