### ISSUE TITLE
compositor.updateSize() does not handle nested scenes

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#205]
`compositor.updateSize()` does not correctly handle a case with nested scenes ([example described here](https://github.com/Famous/engine/issues/183#issuecomment-105657565)) where the size of a scene depends on another scene.

There's a workaround that involves manually calling `compositor.updateSize()` again on nested scene's size change, but it'd be nice if the engine somehow handles this case as well, if possible.

**Comment by michaelobriena** [comment]
I think there is something we can do with the initial mount but updating the inner scene whenever the DOM element that it is mounted into changes size is something that is a bit trickier.  Since the DOM does not give resize events for non body elements, we would have to bake this pretty deep into the implementation.  I think for now, the fact that is is possible is good enough while we talk about how cleanly we could implement this.

One question I have is what usecase are you using nested scenes for?  Where do you see the benefits besides just adding a new subtree to the scene?

**Comment by pilwon** [comment]
@michaelobriena The [linked example](https://github.com/Famous/engine/issues/183#issuecomment-105657565) is the use case. I'd like to render a React component to a DOM element managed by famous but this React component can contain one or more famous scenes. It allows me to reuse existing React components. It also provides developers an option for progressive enhancement with famous.

**Comment by FarhadG** [comment]
What's the status on this issue and PR?

It appears a fix was made for the events, but curious whether a solution was also put forth regarding this issue.

@michaelobriena @DnMllr

**Comment by michaelobriena** [comment]
@pilwon @FarhadG, @alexanderGugel is working on a solution for the ability to get the DOM element associated with a Famous Node.  This will be done via event hooks in the DOM renderer, not as a method on the component itself.

We cannot have nested compositors update their size for free since an html element resizing does not trigger an event and it is not something we want application side since it is a use case we do not want to support for a variety of reasons (Breaks in worker code, breaks in server side code, DOMElements are pooled so it isn't guaranteed to be correct forever, multiple scenes breaks the compositing abstraction).  The event hooks I mentioned will give users the knowledge needed so they can trigger actions to occur when appropriate for their particular integration.

I would like to close this for now because any special casing of nested scenes is not something we are looking to handle at the rendering engine level.
