### ISSUE TITLE
UIEvents misbehave with nested scenes

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#213]
![uievents](https://cloud.githubusercontent.com/assets/61540/7917501/e8a901d4-0858-11e5-8503-8295d6797ae1.gif)

`mouseover` UIEvents are only added to `Scene 1` but `Scene 2` also tries to capture events for some reason.

You can find source code for the above example [here](https://gist.github.com/pilwon/4513365bdb18a7c31779).

**Comment by gadicc** [comment]
I think it's still `Scene 1` capturing the events, since `Scene 2`'s DOMElement is a descendent of `Scene 1`'s DOMElement (in the DOM, I mean).  So that's kind of right in the DOM sense, of events bubbling up... but not sure exactly how we should ideally be handling these kinds of cases :)  I guess the event handler should detect if events are bubbling up from a DOMElement in a different Scene and ignore them?  I'm trying to think if there's any case where we wouldn't want to do that.

**Comment by pilwon** [comment]
We at least know error shouldn't be thrown there.

I think we need a way to control whether events get bubbled up or get discarded at the scene level. Bubbling up may be a sensible default here.

**Comment by trusktr** [comment]
I think two scenarios:

1) Currently Scenes are not agnostic to the web platform because the constructor needs a DOM selector argument. WIth this method of creating scenes, it makes sense that events shouldn't propagate since we can't guarantee that the selected DOM element is inside a Famous scene graph.

2) It'd be super nice if the Scene API was completely agnostic to the web platform (Famous can handle that behind the scenes). In this ideal scenario (@michaelobriena @zackbrown @DnMllr @marklu), the API might look like this:

```js
var target
if (FamousEngine.isWeb) { // in the web
  target = FamousEngine.getTarget($('body')[0]) // returns a Target instance.
}
else if (FamousEngine.isIOS) {
  target = FamousEngine.getTarget(referenceToSomeIPhoneWidgetOrSomething) // returns a Target instance.
}

var node = FamousEngine.createScene(target) // pass the Target instance into the scene constructor
  .addChild()

var scene2 = FamousEngine.createScene(node)
// ^ where/how this scene is rendered is handled internally by Famous. It might be on a DOMElement, or some native container, etc, but we know it's a child of a node. We only care about the Target for the root node.
```

Now we know that `scene2` is explicitly a child of `node` and don't care what what type of things it is rendered in (a DOMElement? a native container of some sort? Who knows).

But in this case it'd make explicit sense for the parent `node` to know of the child `scene2`'s events. 

There could be an option for events to be isolated:

```js
var scene2 = FamousEngine.createScene(node, {bubble: false}) // or similar
```

**Comment by michaelobriena** [comment]
@pilwon Looking into this.

**Comment by pilwon** [comment]
Interestingly enough, this is what you get when you add UIEvent to `scene 2` instead. (`scene 2` is still nested under `scene 1`) I'm still trying to understand what this means.

![uievents2](https://cloud.githubusercontent.com/assets/61540/7925554/1f3a9286-0894-11e5-9b7d-1c94c2edf78b.gif)

**Comment by michaelobriena** [comment]
This is because events from scene 2 are bubbling up to scene 1 because of standard DOM conventions.  We use the path on the element as metadata when we pass it back to the application layer but because that path does not have a registered event in scene 1 our lookup fails.

I think bigger picture we need to decide if nesting scenes is something we want to support as it was not a usecase that we really deemed a viable pattern.

**Comment by pilwon** [comment]
I'd say *yes* to supporting nested scenes if famous encourages its engine being integrated with Angular/React/Meteor/etc and widely adopted.

In a perfect scenario, the integration should allow developers freely enter and leave the famous land. With some workarounds discussed [here](https://github.com/Famous/engine/issues/183) and [there](https://github.com/Famous/engine/issues/205) something like the following is already (sort of) working:

--
#### Component 1
```xml
<Scene>
  <Node>
    <DOMElement>
      <Component2/>
    </DOMElement>
  <Node>
</Scene>
```

#### Component 2
```xml
<div>
  <h1>
    <SomeComponent/>
  </h1>
  <OtherComponent>
    <Scene>
      <Node/>
    </Scene>
  </OtherComponent>
</div>
```

**Comment by michaelobriena** [comment]
Naive fix landed in https://github.com/Famous/engine/tree/v0.5.1

**Comment by pilwon** [comment]
@michaelobriena Could you please link PR or commit instead of tag? This is very difficult for the community to track code changes. Also we'd need to start [keeping a changelog](http://keepachangelog.com/).

**Comment by trusktr** [comment]
I think it's 9d4c05e79fe60a242c00583fa544d91d42762a3d.
