### ISSUE TITLE
Gesture Handler node propagation

### ISSUE THREAD

**Issue by pbrazdil** [Famous/engine#219]
I have one node in the background and several other nodes above it. Node in the background needs to receive Gesture events. However I see no possibility of Gesture propagation from nodes above.

How can I set up GestureHandler so it will capture all gesture events on the page (even from nodes above the background node)?

Setting GestureHandler on root level does not work.

In the old version of famous we just piped surfaces together and it work without any problems, how to do it in Famous Engine?

**Comment by michaelobriena** [comment]
@pbrazdil if you add a component on the root node with an onReceive method you can listen to all click events.

```js
root.addComponent({
    onReceive: function(e, payload) {
        if (e === 'click') {

        }
    }
});
```

This onReceive method on a component is a way to get all of the events that the Node knows about.  I will need to look into how GestureHandler works in particular and which events bubble to parents.

**Comment by FarhadG** [comment]
What's the status on this issue? @pbrazdil, we're curious if @michaelobriena suggestions was useful for your application.

Lookin' forward to having this resolved.

**Comment by pbrazdil** [comment]
It's working but it's low level because it provides directly mouse and touch events. Not gestures as  GestureHandler does.

There need to be way how to propagate gestures similarly as well.

**Comment by alexanderGugel** [comment]
# Solution 1

One way to propagate them is to emit system wide events via `Node#emit` (system as in "restricted to the current scene"). That way all nodes in the scene receive the event and can act accordingly. The "low level" node would filter out the events that should be broadcasted and dispatches a new, more specific event (e.g. "showSidebar") via `Node#emit`.

## Example

The "low-level" node:

```js
node.addComponent({
    onReceive: function(type, ev) {
        if (type === 'click') {
            node.emit('my-event', {
                some: 'data'
            });
        }
    }
});
```

The receiving nodes:

```js
node.addComponent({
    onReceive: function(type, ev) {
        if (type === 'my-event') {
            // ...
        }
    }
})
```

# Solution 2

Another way is to use the dispatch in order to emit events to a specific node ("UI events"). UI Events bubble (just like DOM events). Therefore leaf nodes receive the event before their parents. They can also stop further propagation via `Event#stopPropagation` (looks like DOM, acts as DOM, but isn't DOM).


## Example

```js
var path = node.getLocation();
var dispatch = scene.getDispatch();

node.addComponent({
    onReceive: function(type, ev) {
        if (type === 'click') {
            dispatch.dispatchUIEvent(receivingNode.getLocation(), 'my-event', {
                some: 'data'
            });
        }
    }
});
```

The receiving nodes (same as above):

```js
node.addComponent({
    onReceive: function(type, ev) {
        if (type === 'my-event') {
            // ...
        }
    }
})
```

**Comment by pbrazdil** [comment]
Thank you so much. I can't test it right now, so I will close this issue.

I will be working on it again in few weeks, I will reopen it if it will be needed.
