### ISSUE TITLE
onUpdate Invoked Multiple Times per Frame [Bug or Question]

### ISSUE THREAD

**Issue by jd-carroll** [Famous/engine#340]
Adding an `onUpdate` function to a `Node` and requesting an update from `FamousEngine.requestUpdate` causes the function to be called multiple times.

The issue appears to be in the `FamousEngine` where it has:
```(javascript)
while (queue.length) {
        item = queue.shift();
        if (item && item.update) item.update(time);
        if (item && item.onUpdate) item.onUpdate(time);
}
```
The problem is that in `item.update` it will internally call  (assuming item is a `Node`)
```(javascript)
if (this.onUpdate) this.onUpdate();
```

I believe the code in `FamousEngine` should be something more like:
```(javascript)
while (queue.length) {
        item = queue.shift();
        if (item && item.update) item.update(time);
        **else** if (item && item.onUpdate) item.onUpdate(time);
}
```
But a couple of questions:
- Can we pass any object / primitive into the `FamousEngine.requestUpdate`?
- Is it better practice to move the controller logic out of the Node?  
In this situation I am trying to implement a physics engine which requests updates and thought it appropriate to include in the Node itself.

**Comment by DnMllr** [comment]
This is a bug! Thank you for pointing it out. 

Here are some answers to your questions:
* Yes you can, but you probably shouldn't. We really would like to make the update logic more regular (Doing some sorting rather than just pushing onto a queue, for example) and that might mean that there will be some interface expectations that objects that the FamousEngine is updating must comply with. Things like the PhysicsEngine are a special case (the physics engine will need to be updated every frame always) so we are still figuring out the best way to handle these sorts of things.
* I think nodes should be subclassed to be controllers where necessary. The key thing, though, is that components are probably the best way to extend Nodes with behavior. So the question to ask is if the controller is a behavior or a fundamentally different part of the scene graph. For example, a header, or a slider, might be an extended node, but spinning or a physical interaction is a behavior and that should probably be a component. It sounds like if you are doing things with physics, components are a better way to achieve that control.

**Comment by jd-carroll** [comment]
Ok, I think I'm on the same page.. 

Where my confusion may lie is that in my particular usecase for the `PhysicsEngine`, I am using the `PhysicsEngine` in a scroll-view where all of the child nodes are positioned by the parent scroll-view node.  In this case, I think it is more appropriate to subclass rather than use a component.  

However, the case you highlight would be if I was using the `PhyscisEngine` for some custom animation that does not change the behavior of other (child) nodes?

**Comment by DnMllr** [comment]
@jd-carroll fix in pr #348

**Comment by jd-carroll** [comment]
@DnMllr Thanks! 
I never thought of that, giving each child node a particle / rectangle... Sounds very intruiging

Will keep bug opened until change has been merged.

**Comment by michaelobriena** [comment]
Closing as this landed
