### ISSUE TITLE
Node.prototype.receive is missing

### ISSUE THREAD

**Issue by jd-carroll** [Famous/engine#341]
`Node.prototype.receive` is missing in the latest release and I don't remember seeing anything about this change.  Can someone please provide further details?

Seems to have gone in with this commit: https://github.com/Famous/engine/commit/a3d1bcf3b9a8d4cc81ebc5aa7091e573c33ed11d#diff-20164165518dcfb14298730df6349123L1242

**Comment by DnMllr** [comment]
Receive was deprecated as part of the general eventing changes that made their way in in 0.6. Once again, that was meant to be a smoother process than it turned out to be.

A few months ago the there were three classes that were responsible for the logic that Node was responsible for at release, but they were removed for efficiency reasons. This made the Node class, obviously bloated (its still one of the longer files, if not the longest, in the platform). Part of the goals of the changes with 0.6 was to deemphasize the Node class as the center of most of the scene graph logic in the engine and as such has an incredible amount of methods and logic that it probably never should have had. Most notably, the node class had to be the primary api interface to the famous scene as well as the primary maintainer of the logic of the scene. This has lead to a great deal of confusion about what where the line is between Node's public and private api. I think that this confusion is where the majority of the pain of this version bump is coming from.

In an effort to improve maintainability of the engine, Node's responsibilities are going to become definitively just being an API interface to the systems that make up the famous engine. This decision created the TransformSystem and SizeSystem most notably, and also emphasized the Dispatch as a the manager of the eventing logic.

As such, many methods on Node were removed. Obviously, in the future, these things will be handled much more gracefully.

**Comment by jd-carroll** [comment]
@DnMllr In #342 you mentioned a generic eventing framework where UI events go up and custom events are sent down.  How will the UI events be sent up through the tree?

Lets say I have the following tree:
```
Level | Tree
------|---------------------------------------------------------------------
  1   | CustomNode   // <- This level contains "touchmove" event handlers
      |     |
  2   |    Node      // <- This level contains "click" event handlers
      |   /    \
  3   | Node   Node  // <- This level contains DOMElement's
```

Since the nodes at levels 1 & 2 do not have `DOMElement`'s, they will they will not receive the events generated by level 3.  Or am I missing something?

**Comment by jd-carroll** [comment]
Ok, I apologize for my ignorance but I finally figured it out.  My comments above are inaccurate and the eventing system is in place.
