### ISSUE TITLE
Public API [Question]

### ISSUE THREAD

**Issue by jd-carroll** [Famous/engine#347]
Are any of the following classes considered part of the public API?
- `Compositor`
- `ContainerLoop` / `RequestAnimationFrameLoop`
- `UIManager`

If any of these are considered part of the public API, could we please create public getters in the `FamousEngine`.

If `Compositor and/or `UIManager` are not considered public, why not?  Specifically, access to the `Compositor` is key for being able to send/generate synthetic events for child to parent communication.

**Comment by alexanderGugel** [comment]
The mentioned classes are all considered public, since they need to be used directly in order to set up the worker build. E.g. see https://github.com/Famous/engine-seed/blob/worker/src/index.js#L8

`FamousEngine.init()` can only be used when running everything in the UI thread.

**Comment by jd-carroll** [comment]
@alexanderGugel If they are considered part of the Public API, then the `FamousEngine` should have getters for each one.  Right now there is no direct access to the `Compositor` which will be required if you are trying to pass around (up) custom events.

**Comment by alexanderGugel** [comment]
If you really need to access the Compositor, UIManager, *Loop, they should be instantiated explicitly IMO. Providing getter function will probably just confuse everyone, since the those parts of the engine have to run in the UI thread. The getters wouldn't return anything when running in a worker.

> Right now there is no direct access to the Compositor which will be required if you are trying to pass around (up) custom events.

Can you elaborate on what makes you think so? Our eventing system is completely separated from the actual DOMEvents. E.g. that way we can expose things like `Event#stopPropagation` while actually not having access to the underlying event. We can't and don't need to use the Compositor for that. By "custom events" do you mean `CustomEvent` (which we don't need, since we reimplement event bubbeling anyways) or just events specifically emitted through the `Dispatch`/ `Node#emit`?

**Comment by jd-carroll** [comment]
By custom events I mean application events, not DOM events.  There isn't a good way to send an event up the tree so I was thinking of utilizing the same system the UI DOM events use.  From what I recall, this required access to the `Compositor`.

**Comment by alexanderGugel** [comment]
The compositor handles the actual rendered contexts in the UI thread. A context is basically a root element (real DOM element), a DOMRenderer and (if needed) a WebGLRenderer.

The eventing system you are looking for is implemented in Dispatch.

* https://github.com/Famous/engine/blob/master/core/Dispatch.js#L322
* https://github.com/Famous/engine/blob/master/core/Dispatch.js#L351

**Comment by jd-carroll** [comment]
@alexanderGugel You're probably right, I opened this during the whole breaking change with no doc dilemma. I guess I was looking for something on the `Node` itself and not external.  Will close.
