### ISSUE TITLE
PhysicsEngine Instability && rAF Frame Time

### ISSUE THREAD

**Issue by jd-carroll** [Famous/engine#389]
First of all, let me preface with the `PhysicsEngine` works great and the fact that I am able to bring up the issue below is what I like to call **a good problem to have!**  So a big :clap: for the work by the Famous devs!

Now...

On my local system the PhysicsEngine is very jittery at high velocities.  I will go through all of the details below, however **the core of the issue is that the `PhysicsEngine` will occasionally update multiple times per frame.**  When multiple updates occur it looks like a jump in the rendered items.

I have put together a simple scrollview to demonstrate the issue which is available here:
https://github.com/jd-carroll/engine-seed/tree/scrollViewSample

To illustrate the issue, add the following code in `PhysicsEngine.update`:
```
    ...
    var count = 0;
    while(delta > step) {
        count++;

        ...
    }

    if (count > 1) {
        console.error('PhysicsEngine Stepped Multiple Times!!!  count: ' + count);
    } else if (count === 0) {
        console.error('PhysicsEngine Did Not Step!!!');
    } else {
        console.log('step');
    }

    this.delta = delta;
};
```

This will repeatedly produce the following output:
```
PhysicsEngine.js:400 PhysicsEngine Did Not Step!!!
PhysicsEngine.js:402 step
PhysicsEngine.js:400 PhysicsEngine Did Not Step!!!
PhysicsEngine.js:402 step
PhysicsEngine.js:400 PhysicsEngine Did Not Step!!!
PhysicsEngine.js:402 step
PhysicsEngine.js:400 PhysicsEngine Did Not Step!!!
PhysicsEngine.js:402 step
PhysicsEngine.js:400 PhysicsEngine Did Not Step!!!
PhysicsEngine.js:398 PhysicsEngine Stepped Multiple Times!!!  count: 2
```
When running on my local system, each frame is completed in < 8ms, so from the start of one frame to the start of the next is ~8.3ms.

I think there are multiple issues in play here:
- Only update the `PhysicsEngine` after a certain threshold has been reached
- Maintain consistent frame times

**Updating after threshold**
If the `PhysicsEngine` should only update after a specific threshold (and I'm not convinced that it should), there should be a simple `if (delta > step)` to control entry.

**Consistent Frame Time**
I certainly understand the need to maintain consistent/deterministic frame updates, but I do not feel that placing a `while` loop in `PhysicsEngine.update` is the way to accomplish that.  I think the majority of the responsibility should be delegated to the `UIManager`.  If I understand the current code correctly, as soon as one frame ends, the looper will just as quickly request the next frame.  

The `UIManager` and `RequestAnimationFrame` (looper) should become smarter about how/when they request frames.  Ideally, it should behave something along the lines of:
- The `UIManager` should be given a target frame rate (fps) as an option and otherwise default to 60fps.
- Instead of the `RequestAnimationFrame` automatically requesting the next frame, the `UIManager` should control the request for the next frame.
- After each frame completes and before requesting the next frame, the `UIManager` should calculate the the total time it took to complete that frame.
- If the total time it took to complete the frame exceeded the target rate, then it should immediately request the next frame.  Otherwise it should request the next frame after a delay of what ever remaining time it as to meet its target.
- The `UIManager` should maintain a history of frame times.  The history could be set by an option with a default of say 100.  The index for the array would be calculated like 
`frameIndex = frameIndex++ % 100 // or options.history`
- The history object will only contain entries for the frames that exceeded the target frame time.
- If 5% of the frames in the history exceeded the target frame time, the frame time should be increased (slower) by 5%.  (Both thresholds could be set by option)
- If 100% of the frames in the history met the frame time (no entries in the history object) *and* the frame rate was previously increased (slower), the frame rate should be decreased (faster) by 5%.  After the next 100 frames the same calculation should be re-run until the frame rate returns to the target rate.

The history would only maintain values for the frames which exceeded the frame time.  This way it is not necessary to iterate over all entries to find the frames we are interested in.

This would allow for a means to achieve very consistent frame rates, which is better than very fast frame rates IMO.  This would also give the application the opportunity to tune itself for optimal performance in resource constrained environments. 

**Having tuned frame rates would also eliminate the need to "gate" the `PhysicsEngine.update`.  It would simply be able to calculate the delta and then perform the update.**

**Comment by jd-carroll** [comment]
I should note that for the example to work you need to change the following line:
https://github.com/Famous/engine/blob/master/physics/PhysicsEngine.js#L332

To:
`var dt = step;`

See #382 for details

**Comment by browles** [comment]
The PhysicsEngine can't jump into the future, and is always strictly behind where it 'should' be and won't be closer than `step` to the current time. The reason why it can step more than once per frame is so that motion remains consistent between different devices/scenarios/page refreshes. If you have specified a `step` of 16ms, and for whatever reason the browser is refreshing at 30 fps (or every 32ms or so), the PhysicsEngine needs to step twice per frame in order to stay up to date. However, on another device capable of running the app at 60fps, we need to see the exact same animation (i.e. same trajectories and speeds), just at a smoother fps. The only way to make the animation consistent is:
- let the PhysicsEngine maintain its own frame rate (by specifying `step`), else motion becomes highly variable across different situations (making e.g. a consistent circular orbit impossible)
- let the PhysicsEngine step potentially more than once per `requestAnimationFrame` frame, else the speed of the animation would vary (indeed making it jumpy at times), even while the trajectories stay accurate

You can actually opt out of having the PhysicsEngine step more than once, by specifying `frameDependent: true` in the initialization options. This will improve performance but will the speed of your animations inconsistent.

If jitteriness is a problem, the first thing I would try is lowering the `step`, precisely so that the PhysicsEngine steps more often. 

Also, in your example, 
```
        this._particle.drag = new physics.Drag(this._particle.body, {
            type: physics.Drag.QUADRATIC,
            strength: -0.001
        });
```
passing a negative constant as the `strength` only makes the `Drag` a propulsive force, instead of slowing the bodies down. This is likely the cause of some of your increasing velocities.

**Comment by jd-carroll** [comment]
Closing this as there were multiple problems:
1. I had an extra requestUpdate in the `mount`
2. Sometime you need to be greedy
